# Generated by Django 3.2.5 on 2022-10-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
    ]
